import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    /**
     * [acra website](http://acra.ch) */
    const val acra: String = "4.9.2" // available milestone: "4.11" 

    const val com_afollestad_material_dialogs_core: String =
            "0.9.6.0" // available milestone: "2.0.0-beta4" 

    /**
     * [constraint-layout website](http://tools.android.com) */
    const val constraint_layout: String = "1.1.2" // available milestone: "2.0.0-alpha2" 

    /**
     * [appcompat-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat_v7: String = "27.0.2" // available milestone: "28.0.0" 

    /**
     * [cardview-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val cardview_v7: String = "27.0.2" // available milestone: "28.0.0" 

    /**
     * [customtabs website](http://developer.android.com/tools/extras/support-library.html) */
    const val customtabs: String = "27.0.2" // available milestone: "28.0.0" 

    /**
     * [design website](http://developer.android.com/tools/extras/support-library.html) */
    const val design: String = "27.0.2" // available milestone: "28.0.0" 

    const val multidex_instrumentation: String = "1.0.2" // available milestone: "1.0.3" 

    const val multidex: String = "1.0.2" // available milestone: "1.0.3" 

    /**
     * [preference-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val preference_v7: String = "27.0.2" // available milestone: "28.0.0" 

    /**
     * [recyclerview-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val recyclerview_v7: String = "27.0.2" // available milestone: "28.0.0" 

    /**
     * [support-annotations website](http://developer.android.com/tools/extras/support-library.html) */
    const val support_annotations: String = "27.0.2" // available milestone: "28.0.0" 

    /**
     * [support-v4 website](http://developer.android.com/tools/extras/support-library.html) */
    const val support_v4: String = "27.0.2" // available milestone: "28.0.0" 

    /**
     * [aapt2 website](https://developer.android.com/studio) */
    const val aapt2: String = "3.2.0-4818971" // available milestone: "3.4.0-alpha01-5013011" 

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String =
            "3.2.0" // available milestone: "3.4.0-alpha01" 

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "26.2.0" // available milestone: "26.4.0-alpha01" 

    /**
     * [conductor-support website](https://github.com/bluelinelabs/Conductor) */
    const val com_bluelinelabs: String = "2.1.5" // up-to-date

    /**
     * [material-design-dimens website](https://github.com/DmitryMalkovich/material-design-dimens) */
    const val material_design_dimens: String = "1.4" // up-to-date

    /**
     * [android-job website](https://github.com/evernote/android-job) */
    const val android_job: String = "1.2.5" // available milestone: "1.3.0-alpha08" 

    /**
     * [rx-preferences website](https://github.com/f2prateek/rx-preferences) */
    const val rx_preferences: String = "1.0.2" // up-to-date

    const val textdrawable: String = "558677e" 
            /* Could not resolve com.github.amulyakhare:TextDrawable:+. 
            .... */

    /**
     * [compiler website](https://github.com/bumptech/glide) */
    const val com_github_bumptech_glide: String = "4.6.1" // available milestone: "4.8.0" 

    /**
     * [PhotoView website](https://github.com/chrisbanes/PhotoView) */
    const val photoview: String = "2.1.3" // available milestone: "2.2.0" 

    /**
     * [library website](https://github.com/dmytrodanylyk/android-process-button) */
    const val com_github_dmytrodanylyk_android_process_button_library: String =
            "1.0.4" // up-to-date

    /**
     * [changelog website](https://github.com/gabrielemariotti/changeloglib) */
    const val changelog: String = "2.1.0" // up-to-date

    /**
     * [java-nat-sort website](https://github.com/gpanther/java-nat-sort) */
    const val java_nat_sort: String = "natural-comparator-1.1" // up-to-date

    /**
     * [injekt-core website](https://github.com/kohesive/injekt) */
    const val injekt_core: String = "65b0440" // exceed the version found: v1.3.0

    const val directionalviewpager: String = "3acc51a" 
            /* Could not resolve com.github.inorichi:DirectionalViewPager:+. 
            .... */

    const val junrar_android: String = "634c1f5" 
            /* Could not resolve com.github.inorichi:junrar-android:+. 
            .... */

    /**
     * [subsampling-scale-image-view website](https://github.com/davemorrissey/subsampling-scale-image-view) */
    const val subsampling_scale_image_view: String = "ac0dae7" // available milestone: "v3.4.1" 

    const val unifile: String = "e9ee588" // available milestone: "1.0.0" 

    const val slice: String = "v1.2" // up-to-date

    /**
     * [reactivenetwork website](https://github.com/pwittchen/ReactiveNetwork) */
    const val reactivenetwork: String = "0.7.0" // available milestone: "0.12.4" 

    /**
     * [kotson website](https://github.com/SalomonBrys/Kotson) */
    const val kotson: String = "2.5.0" // up-to-date

    /**
     * [android-shortcut-gradle-plugin website](https://github.com/Zellius/android-shortcut-gradle-plugin) */
    const val android_shortcut_gradle_plugin: String = "0.1.2" // up-to-date

    const val play_services_gcm: String = "11.8.0" // available milestone: "16.0.0" 

    /**
     * [gson website](https://github.com/google/gson) */
    const val gson: String = "2.8.2" // available milestone: "2.8.5" 

    const val firebase_core: String = "11.8.0" // available milestone: "16.0.4" 

    /**
     * [google-services website](http://tools.android.com/) */
    const val google_services: String = "3.2.0" // available milestone: "4.1.0" 

    /**
     * [rxbinding-appcompat-v7-kotlin website](https://github.com/JakeWharton/RxBinding/) */
    const val com_jakewharton_rxbinding: String = "1.0.1" // up-to-date

    const val rxrelay: String = "1.2.0" // up-to-date

    /**
     * [timber website](https://github.com/JakeWharton/timber) */
    const val timber: String = "4.6.1" // available milestone: "4.7.1" 

    /**
     * [disklrucache website](https://github.com/JakeWharton/DiskLruCache/) */
    const val disklrucache: String = "2.0.2" // up-to-date

    /**
     * [viewstatepageradapter website](https://github.com/NightlyNexus/ViewStatePagerAdapter/) */
    const val viewstatepageradapter: String = "1.0.4" // up-to-date

    const val filepicker: String = "2.5.2" // available milestone: "4.2.1" 

    /**
     * [sqlite website](https://github.com/pushtorefresh/storio) */
    const val sqlite: String = "1.13.0" // up-to-date

    /**
     * [duktape-android website](https://github.com/square/duktape-android) */
    const val duktape_android: String = "1.2.0" // available milestone: "1.3.0" 

    /**
     * [okhttp website](https://github.com/square/okhttp) */
    const val okhttp: String = "3.10.0" // available milestone: "3.11.0" 

    /**
     * [okio website](https://github.com/square/okio/) */
    const val okio: String = "1.14.0" // available milestone: "2.1.0" 

    /**
     * [adapter-rxjava website](https://github.com/square/retrofit/) */
    const val com_squareup_retrofit2: String = "2.3.0" // available milestone: "2.4.0" 

    /**
     * [flexible-adapter-ui website](https://github.com/davideas/FlexibleAdapter) */
    const val flexible_adapter_ui: String = "1.0.0-b1" // available milestone: "1.0.0" 

    /**
     * [flexible-adapter website](https://github.com/davideas/FlexibleAdapter) */
    const val flexible_adapter: String = "5.0.0-rc4" // available milestone: "5.1.0" 

    /**
     * [nucleus-support-v7 website](https://github.com/konmik/nucleus) */
    const val info_android15_nucleus: String = "3.0.0" // available milestone: "6.0.0" 

    /**
     * [rxandroid website](https://github.com/ReactiveX/RxAndroid) */
    const val rxandroid: String = "1.2.1" // up-to-date

    /**
     * [rxjava website](https://github.com/ReactiveX/RxJava) */
    const val rxjava: String = "1.3.6" // available milestone: "1.3.8" 

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.5" // up-to-date

    const val glide_transformations: String = "3.1.1" // available milestone: "3.3.0" 

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "4.12" // up-to-date

    /**
     * [library website](https://github.com/2dxgujun/AndroidTagGroup) */
    const val me_gujun_android_taggroup_library: String = "1.4" // available milestone: "1.5" 

    /**
     * [library website](https://github.com/DreaminginCodeZH/SystemUiHelper) */
    const val me_zhanghai_android_systemuihelper_library: String = "1.0.0" // up-to-date

    /**
     * [assertj-core website](http://assertj.org) */
    const val assertj_core: String = "1.7.1" // available milestone: "3.11.1" 

    /**
     * [kotlin-android-extensions-runtime website](https://kotlinlang.org/) */
    const val org_jetbrains_kotlin: String = "1.2.71" // available milestone: "1.3.0-rc-190" 

    /**
     * [kotlinx-coroutines-android website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val org_jetbrains_kotlinx: String = "0.22.2" // available milestone: "1.0.0-RC1" 

    /**
     * [jsoup website](https://jsoup.org/) */
    const val jsoup: String = "1.10.2" // available milestone: "1.11.3" 

    /**
     * [mockito-core website](https://github.com/mockito/mockito) */
    const val mockito_core: String = "1.10.19" // available milestone: "2.23.0" 

    /**
     * [robolectric website](http://robolectric.org) */
    const val org_robolectric: String = "3.1.4" // available milestone: "4.0-beta-1" 

    /**
     *
     *   To update Gradle, edit the wrapper file at path:
     *      ./gradle/wrapper/gradle-wrapper.properties
     */
    object Gradle {
        const val runningVersion: String = "4.6"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.1-20181022040056+0000"

        const val releaseCandidate: String = ""
    }
}
